### ISSUE TITLE
handling pre-commit hooks for check-manifest

### ISSUE THREAD

**Issue by kratsg** [diana-hep/pyhf#485]
# Question

We can't have a precommit hook for check-manifest as it fails harder than `black` which simply warns...

```
- repo: https://github.com/mgedmin/check-manifest
    rev: "0.39"
    hooks:
    - id: check-manifest
      language_version: python3.6
```

# Relevant Issues and Pull Requests

See #481 which introduced `check-manifest`.
